#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cwd=$(pwd)

dir=$(mktemp -d)
echo "Working dir: $dir"
cd "$dir"

echo | sqlite3 timings.db <<- EOM
CREATE TABLE events (package TEXT, module TEXT, phase TEXT, alloc INTEGER, time REAL);
EOM

touch failures
NUM_PROCESSED=$(find "$cwd" -name "*.dump-timings" -printf '.' -exec $SCRIPT_DIR/scripts/process timings.tsv failures {} \; | wc -c)
NUM_FAILURES=$(cat failures | wc -l)
NUM_EVENTS=$(cat timings.tsv | wc -l)

echo "Processed $NUM_PROCESSED *.dump-timings files containing $NUM_EVENTS events"
if (( "$NUM_FAILURES" > 0 )); then
    echo "Failed to parse $NUM_FAILURES lines"
fi

commandfile=$(mktemp)
cat <<EOF > $commandfile
.mode tabs events
.import /dev/stdin events
EOF

cat timings.tsv | sqlite3 --init "$commandfile" "timings.db"

echo "{" > data.json
echo "\"phasesByTime\": $(sqlite3 -json timings.db "select phase, sum(time) as time from events group by phase order by sum(time) desc;")," >> data.json
echo "\"phasesByAlloc\": $(sqlite3 -json timings.db "select phase, sum(alloc) as alloc from events group by phase order by sum(time) desc;")," >> data.json
echo "\"modules\": $(sqlite3 -json timings.db "select module from events group by module order by module;")," >> data.json
echo "\"data\": $(sqlite3 -json timings.db "select module, phase, sum(time) as time, sum(alloc) as alloc from events group by module, phase;")," >> data.json
echo "}" >> data.json

node $SCRIPT_DIR/index.js $(pwd)/data.json
